name = "Difmap"
uuid = "697f6f98-b792-4bca-85fe-71b3d053de65"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.12"

[deps]
difmap_jll = "43cd2700-e54a-5645-adf8-b9b288a87fe6"

[compat]
difmap_jll = "2.5"
julia = "1.6"
