name: Export Pluto notebooks
on:
    push:
        branches:
            - main
            - master
    workflow_dispatch:

env:
  PYTHON:

jobs:
    build-and-deploy:
        runs-on: macos-13
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Julia
              uses: julia-actions/setup-julia@v1
              with:
                  version: 1

            - name: Run & export Pluto notebooks
              run: |
                julia -e 'using Pkg
                  Pkg.activate(mktempdir())
                  Pkg.add([
                    Pkg.PackageSpec(name="PlutoSliderServer", version="0.3.2-0.3"),
                  ])
                  import PlutoSliderServer
                  PlutoSliderServer.github_action(".";
                    Export_cache_dir="pluto_state_cache",
                    Export_baked_notebookfile=false,
                    Export_baked_state=false,
                    # more parameters can go here
                  )'
            - name: Deploy to gh-pages
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: .